package ascent.domgen.aria

/** Renders parsed [[AriaProperty]] entries (from `aria-query`'s vendored data) into the generated
  * `dom-types/.../generated/AriaAttrs.scala` file.
  *
  * Mirrors the shape of the existing hand-written `AriaAttrs.scala` so the cutover is a direct swap with no call-site
  * changes:
  * {{{
  *   object AriaAttrs:
  *     val ariaLabel: AttrKey[String] = AttrKey("aria-label", Codec.StringAsIs)
  *     val ariaPressed: AttrKey[Boolean] = AttrKey("aria-pressed", Codec.BooleanAsTrueFalse)
  *     ...
  * }}}
  *
  * Type & codec selection follows the ARIA spec convention (boolean attributes serialize to literal `"true"` /
  * `"false"` strings, NOT HTML's presence-flag form).
  */
object AriaRenderer:

  private val header =
    """// AUTO-GENERATED by ascent-domgen. Do not edit by hand — see domgen/README.md to regenerate.
      |""".stripMargin

  /** Render the full source file: header + package + `object AriaAttrs` body. */
  def render(properties: List[AriaProperty]): String =
    val ariaLines = properties.map(renderOne).mkString("\n")
    s"""$header
       |package ascent.domtypes
       |
       |/** ARIA attribute keys, generated from the vendored `aria-query` snapshot.
       |  *
       |  * ARIA isn't part of webref's IDL (its attributes aren't surfaced as JS properties on
       |  * any DOM interface — they're authored as plain HTML attributes), so we generate this
       |  * catalog from `aria-query`'s structured JS data instead. Same shape as the generated
       |  * [[Attrs]]: each property is an [[AttrKey]] with the codec required by the ARIA spec
       |  * (boolean attrs serialize to literal `"true"`/`"false"`, NOT HTML's presence-flag).
       |  *
       |  * `role` is included here too — not strictly an ARIA attribute, but the same authoring
       |  * concern (assistive-tech metadata layered on top of HTML).
       |  */
       |object AriaAttrs:
       |
       |  /** The `role` attribute — assistive-tech semantic descriptor, not an ARIA attribute
       |    * proper. Hand-written here because aria-query doesn't list it (its dataset is
       |    * focused on properties + states); every consumer wants it on the same namespace.
       |    */
       |  val role: AttrKey[String] = AttrKey("role", Codec.StringAsIs)
       |
       |$ariaLines
       |""".stripMargin
  end render

  /** Render one ARIA property as an `AttrKey[T] = AttrKey("dom-name", codec)` line. */
  private def renderOne(p: AriaProperty): String =
    val (scalaType, codec) = scalaTypeAndCodec(p.`type`)
    s"""  val ${scalaName(p.name)}: AttrKey[$scalaType] = AttrKey("${p.name}", $codec)"""

  /** Map an aria-query type flag to (Scala type, Codec ref).
    *
    * Pragmatic choice for `tristate`: emit as `Boolean` so the common case (`ariaPressed(true)`, `ariaChecked(false)`)
    * is ergonomic. The third spec value `"mixed"` is rare; users who need it set the attribute via the dom-name string
    * (`Attr.StaticAttr("aria-checked", AttrValue.Str("mixed"))`).
    */
  private def scalaTypeAndCodec(typeFlag: String): (String, String) =
    typeFlag match
      case "boolean"  => "Boolean" -> "Codec.BooleanAsTrueFalse"
      case "tristate" => "Boolean" -> "Codec.BooleanAsTrueFalse"
      case "integer"  => "Int"     -> "Codec.IntAsString"
      // Everything else (string, id, idlist, token, tokenlist) — String.
      case _ => "String" -> "Codec.StringAsIs"

  /** Camel-case `aria-foo-bar` → `ariaFooBar`. The aria-query property names are mostly single-word after the prefix
    * (`aria-pressed`, `aria-label`) so this is one capitalize. Keep symmetry with the existing hand-written naming.
    */
  private def scalaName(domName: String): String =
    val parts = domName.split('-').toList
    parts match
      case Nil          => domName
      case head :: tail => head + tail.map(s => if s.isEmpty then s else s.head.toUpper.toString + s.tail).mkString

end AriaRenderer
