package ascent.domgen

/** Renders the def model ([[ElementDef]] / [[AttrDef]] / [[EventDef]] / [[FacadeDef]]) into Scala source strings.
  *
  * Each method produces one self-contained source file's contents. The strings are intended to be **committed to the
  * repo** under `dom-types/.../generated/` (platform-neutral) and `dom-facade/.../generated/` (js-only event facades),
  * so reviewers can see exactly what the generator emits in PR diffs. Anything emitted here must compile in its target
  * module without any extra dependencies — that's enforced by step 3 (compile the generated output as the acceptance
  * gate).
  */
object Renderer:

  private val header =
    """// AUTO-GENERATED by ascent-domgen. Do not edit by hand — see domgen/README.md to regenerate.
      |""".stripMargin

  /** Scala 3 hard keywords that MUST be backticked when used as identifiers. Soft keywords (e.g. `inline`, `using`)
    * compile bare in identifier position so they are deliberately absent from this list. Renderer always backticks
    * anything in this set.
    */
  private val scalaKeywords: Set[String] = Set(
    "abstract",
    "case",
    "catch",
    "class",
    "def",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "false",
    "final",
    "finally",
    "for",
    "given",
    "if",
    "implicit",
    "import",
    "lazy",
    "match",
    "new",
    "null",
    "object",
    "override",
    "package",
    "private",
    "protected",
    "return",
    "sealed",
    "super",
    "then",
    "this",
    "throw",
    "trait",
    "true",
    "try",
    "type",
    "val",
    "var",
    "while",
    "with",
    "yield",
  )

  /** Wraps an identifier in backticks if it would otherwise be a Scala 3 keyword. */
  private[domgen] def safeId(name: String): String =
    if scalaKeywords.contains(name) then s"`$name`" else name

  /** Ergonomic plain-identifier aliases for keyword-named members. The spec-faithful backticked key is always emitted
    * (`A.`type``); the alias is an ADDITIONAL `val` pointing at it so an author can write the noise-free `A.typ`. Keyed
    * by `scalaName`; only members with a natural plain name are listed, so we never invent ugly `classAttr`-style
    * identifiers.
    */
  private[domgen] val identAliases: Map[String, String] = Map(
    "type" -> "typ"
  )

  // --- dom-types/.../generated/Elements.scala ---

  def elements(defs: List[ElementDef]): String =
    val vals = defs
      .map { d =>
        // Void elements get a distinct VoidElementKey so the DSL constructor rejects children at
        // compile time; everything else is a normal ElementKey.
        if d.isVoid then s"""  val ${safeId(d.scalaName)}: VoidElementKey = VoidElementKey("${d.domName}")"""
        else s"""  val ${safeId(d.scalaName)}: ElementKey = ElementKey("${d.domName}")"""
      }
      .mkString("\n")
    s"""$header
       |package ascent.domtypes
       |
       |/** All HTML element keys, generated from the vendored webref `elements/html.json`. */
       |object Elements:
       |$vals
       |""".stripMargin
  end elements

  // --- dom-types/.../generated/Attrs.scala ---

  /** Scala value type for an attribute given its codec — kept here in lockstep with [[CodecRef]]. If you add a new
    * codec ref, add the type mapping here and update the relevant tests.
    */
  private def codecValueType(c: CodecRef): String = c match
    case CodecRef.StringAsIs            => "String"
    case CodecRef.IntAsString           => "Int"
    case CodecRef.DoubleAsString        => "Double"
    case CodecRef.BooleanAsAttrPresence => "Boolean"
    case CodecRef.BooleanAsTrueFalse    => "Boolean"

  def attrs(defs: List[AttrDef]): String =
    val vals = defs
      .map { d =>
        val v    = codecValueType(d.codec)
        val main = s"""  val ${safeId(d.scalaName)}: AttrKey[$v] = AttrKey("${d.domName}", ${d.codec.render})"""
        // Emit an ergonomic plain alias for keyword-named attrs (e.g. `typ` -> `type`), so authors
        // can avoid the backtick noise. The alias just points at the canonical backticked val.
        identAliases.get(d.scalaName) match
          case Some(alias) => s"$main\n  val $alias: AttrKey[$v] = ${safeId(d.scalaName)}"
          case None        => main
      }
      .mkString("\n")
    s"""$header
       |package ascent.domtypes
       |
       |/** All HTML attribute keys, generated from the vendored webref IDL.
       |  *
       |  * Each [[AttrKey]] carries the canonical dom name plus the [[Codec]] that converts a typed
       |  * Scala value into a platform-neutral [[AttrValue]] for the DOM backend.
       |  */
       |object Attrs:
       |$vals
       |""".stripMargin
  end attrs

  // --- dom-types/.../generated/Events.scala ---

  def events(defs: List[EventDef]): String =
    val vals = defs
      .map { d =>
        s"""  val ${safeId(d.scalaName)}: EventKey = EventKey("${d.domName}", "${d.eventTypeString}")"""
      }
      .mkString("\n")
    s"""$header
       |package ascent.domtypes
       |
       |/** All DOM event keys, generated from the vendored webref `events.json`.
       |  *
       |  * The event interface type is carried as a STRING (e.g. "ascent.dom.PointerEvent") so this
       |  * file remains platform-neutral and `dom-types` has no facade dependency. The js-side typed
       |  * event DSL resolves the string to the real `@js.native` facade at the binding boundary.
       |  */
       |object Events:
       |$vals
       |""".stripMargin
  end events

  // --- js/.../generated/TypedEvents.scala ---

  /** Render the typed event handler DSL into the `js` module.
    *
    * For each [[EventDef]] we emit a factory `def onClick(handler: dom.PointerEvent => UIO[Unit]): Attr` that wraps the
    * handler in an `Attr.EventHandler`, casting the platform-neutral [[ascent.ast.AscentEvent]]'s `raw` field to the
    * spec-correct dom subtype. The rendered file lives in the `js` module (it imports `ascent.dom` and
    * `ascent.ast.Attr`), so user code that wants typed events does `import ascent.js.TypedEvents.*`.
    *
    * Why this lives in `js`, not `dom-types`: dom-types must stay platform-neutral (Laminar's cross-platform trick);
    * the typed cast can only happen where dom is real.
    */
  def typedEvents(defs: List[EventDef]): String =
    val factories = defs
      .map { d =>
        val eventTpe = d.eventTypeString // e.g. "ascent.dom.PointerEvent"
        val shortTpe = eventTpe.split('.').last
        s"""  /** `${safeId(d.scalaName)}` → $shortTpe. */
         |  def ${safeId(d.scalaName)}[R](handler: $eventTpe => zio.URIO[R, Unit]): Attr[R] =
         |    Attr.EventHandler("${d.domName}", e => handler(e.raw.asInstanceOf[$eventTpe]))""".stripMargin
      }
      .mkString("\n")
    val syncFactories = defs
      .map { d =>
        val eventTpe = d.eventTypeString
        s"""    def ${safeId(d.scalaName)}(handler: $eventTpe => Unit): Attr[Any] =
         |      Attr.EventHandler("${d.domName}", e => zio.ZIO.attempt(handler(e.raw.asInstanceOf[$eventTpe])).orDie)""".stripMargin
      }
      .mkString("\n")
    s"""$header
       |package ascent.js
       |
       |import ascent.ast.Attr
       |
       |/** Typed event-handler DSL, generated from the vendored webref `events.json`.
       |  *
       |  * Each `onXxx(handler)` produces an [[Attr]] suitable for placing on an element. The
       |  * handler receives the spec-correct typed event (e.g. `dom.PointerEvent` for `onClick`,
       |  * `dom.KeyboardEvent` for `onKeyDown`) — no `js.Dynamic` casts at the call site. The handler
       |  * is total: discharge failures with ZIO's own operators; its environment `R` is provided at mount.
       |  *
       |  * Two flavours per event:
       |  *   - `onXxx(handler: Event => UIO[Unit])` — effectful handler (compose / recover with ZIO).
       |  *   - `sync.onXxx(handler: Event => Unit)` — a plain side-effecting block, lifted via
       |  *     `ZIO.attempt`. The mount runs a handler's synchronous prefix inline on the dispatch
       |  *     stack (runOrFork), so a `sync` handler's DOM calls take effect DURING dispatch — what
       |  *     `preventDefault` / drag-and-drop require — and a throw is logged, not lost.
       |  *
       |  * Usage:
       |  * {{{
       |  *   import ascent.js.TypedEvents.*
       |  *   Elements.button(onClick(e => Console.printLine(s"x=${"$"}{e.clientX}")), "Click")
       |  *
       |  *   import ascent.js.TypedEvents.sync.*
       |  *   Elements.button(onClick(e => println(e.clientX)), "Click")
       |  * }}}
       |  */
       |object TypedEvents:
       |$factories
       |
       |  /** Synchronous-handler variants — `Ev.sync.onClick { e => ... }`, or `import
       |    * ascent.js.TypedEvents.sync.*` for bare names. Each lifts a `Event => Unit` block via
       |    * `ZIO.attempt(...).orDie`; the mount logs any throw. */
       |  object sync:
       |$syncFactories
       |""".stripMargin
  end typedEvents

  // --- dom-facade/.../generated/Facades.scala ---

  def facades(defs: List[FacadeDef]): String =
    val classes = defs
      .map { d =>
        val parent = d.parent.getOrElse("js.Object")
        // Drop members whose names collide with java.lang.Object's, mirror of the
        // Interfaces.scala renderer.
        val attrs     = d.members.filterNot(m => objectMethodClashes.contains(m.name))
        val methods   = d.methods.filterNot(m => objectMethodClashes.contains(m.scalaName))
        val attrLines = attrs.map(m => s"  def ${safeId(m.name)}: ${m.scalaType} = js.native")
        // Same overload-defaults rule as Interfaces.scala: defaults only on the longest
        // overload of each name.
        val overloadedNames = methods.groupBy(_.scalaName).filter(_._2.size > 1).keySet
        val keepDefaultsFor =
          overloadedNames.map(n => (n, methods.filter(_.scalaName == n).map(_.params.size).max))
        val methodLines = methods.map { m =>
          val isLongest     = keepDefaultsFor.contains((m.scalaName, m.params.size))
          val allowDefaults = !overloadedNames.contains(m.scalaName) || isLongest
          val params        = m.params
            .map { p =>
              val base = s"${safeId(p.name)}: ${p.scalaType}"
              if p.optional && allowDefaults then s"$base = js.native" else base
            }
            .mkString(", ")
          s"  def ${safeId(m.scalaName)}($params): ${m.returnType} = js.native"
        }
        val body      = (attrLines ++ methodLines).mkString("\n")
        val bodyBlock = if body.isEmpty then "" else s":\n$body\n"
        s"""@js.native
         |@JSGlobal
         |class ${d.interface} extends $parent$bodyBlock""".stripMargin
      }
      .mkString("\n\n")
    s"""$header
       |package ascent.dom
       |
       |import scala.scalajs.js
       |import scala.scalajs.js.annotation.JSGlobal
       |
       |/** Typed event-interface facades, generated from the vendored webref IDL.
       |  *
       |  * These are our own `@js.native` replacements for scalajs-dom's event hierarchy. The DSL's
       |  * typed event handlers (e.g. `onClick: dom.MouseEvent => UIO[Unit]`) bind to these types.
       |  */
       |
       |$classes
       |""".stripMargin
  end facades

  // --- dom-facade/.../generated/Interfaces.scala ---

  /** Render every non-mixin, non-element, non-event interface as a `@js.native` class.
    *
    * Each class has:
    *   - all attributes (own + inherited + mixin-merged) as `def <name>: <Type> = js.native`
    *   - all methods (same walk) as `def <name>(<params>): <ReturnType> = js.native`
    *
    * Method param types use the [[DefBuilder.scalaFacadeType]] resolver, which emits `js.FunctionN[..., R]` for
    * callback typedefs and bare interface names when the IDL defines them. Anything else falls through to `js.Any`.
    */
  def interfaces(defs: List[InterfaceDef]): String =
    val classes = defs.map(renderInterface).mkString("\n\n")
    s"""$header
       |package ascent.dom
       |
       |import scala.scalajs.js
       |import scala.scalajs.js.annotation.JSGlobal
       |
       |/** Generated `@js.native` typed interfaces, from the vendored webref IDL.
       |  *
       |  * Covers everything that's not an HTML element key (in `domtypes.Elements`), an HTML
       |  * attribute key (in `domtypes.Attrs`), or an event interface (in `Facades.scala`).
       |  * Examples: `Window`, `Performance`, `Document`, `CanvasRenderingContext2D`, `Node`.
       |  *
       |  * **Inheritance**: a generated class extends its IDL parent IF that parent is also
       |  * generated (and not an engine-owned interface kept in `EngineFacade.scala`). Otherwise
       |  * it falls back to `js.Object` so the file always compiles.
       |  *
       |  * **Method param types**: callback typedefs (`FrameRequestCallback`, `EventListener`)
       |  * resolve to typed `js.FunctionN[..., R]`. Other named types resolve to the bare
       |  * interface name when defined in the IDL, otherwise `js.Any`.
       |  */
       |
       |$classes
       |""".stripMargin
  end interfaces

  /** Method names that would clash with `java.lang.Object` members and CANNOT be resolved by back-ticking — the binding
    * still collides. Drop these from a generated class so the inherited `Object` member supplies them. (`notify` etc.
    * on a DOM type are real spec methods, but Scala / JVM interop can't express the override; users that need them can
    * drop to `el.asInstanceOf[js.Dynamic].notify(...)`.)
    */
  private val objectMethodClashes: Set[String] =
    Set("clone", "wait", "notify", "notifyAll", "finalize", "valueOf", "toString", "hashCode", "equals")

  // --- dom-facade/.../generated/Dictionaries.scala ---

  /** Render every WebIDL dictionary as a `@js.native trait` with `var`-typed fields.
    *
    * Inheritance via `extends` so users can pass a child where a parent is expected. Construction at the call site uses
    * Scala 3's anonymous class literal:
    * {{{
    *   button.addEventListener("click", handler, new AddEventListenerOptions { passive = true })
    * }}}
    *
    * Required fields and optional fields both emit as `var` — JS-side they're identical (the `required` distinction is
    * enforced by callers, not the runtime). The renderer doesn't currently emit a separate "constructor with all
    * required args" helper; users build the literal at the call site.
    */
  def dictionaries(defs: List[DictionaryDef]): String =
    val classes = defs.map(renderDictionary).mkString("\n\n")
    s"""$header
       |package ascent.dom
       |
       |import scala.scalajs.js
       |
       |/** Generated `@js.native trait`s, one per WebIDL `dictionary` block.
       |  *
       |  * Dictionaries model JS option-objects passed to APIs that take a named-arg
       |  * config (`AddEventListenerOptions`, `KeyboardEventInit`, etc.). Construct via:
       |  * {{{
       |  *   new MyDictionary { foo = "bar"; baz = 42 }
       |  * }}}
       |  */
       |
       |$classes
       |""".stripMargin
  end dictionaries

  private def renderDictionary(d: DictionaryDef): String =
    val parent     = d.parent.getOrElse("js.Object")
    val fieldLines = d.fields.map(f => s"  var ${safeId(f.name)}: ${f.scalaType} = js.native").mkString("\n")
    val body       = if fieldLines.isEmpty then "" else s":\n$fieldLines\n"
    s"""@js.native
       |trait ${d.name} extends $parent$body""".stripMargin

  // --- dom-types/.../generated/Enums.scala (real Scala 3 enums, platform-neutral) ---

  /** Render every WebIDL enum as a REAL Scala 3 `enum`, into `dom-types` (jvm/js/native, zero scalajs dependency) — not
    * a stringly-typed stand-in. Each case carries its wire-correct literal via a `domValue` field:
    * {{{
    *   enum ShadowRootMode(val domValue: String):
    *     case Open extends ShadowRootMode("open")
    *     case Closed extends ShadowRootMode("closed")
    *   object ShadowRootMode:
    *     def fromDom(domValue: String): Option[ShadowRootMode] = values.find(_.domValue == domValue)
    * }}}
    *
    * This is sound at every consumer: `dom-core`'s structural traits (generated by [[structuralTraits]]) reference this
    * type DIRECTLY (both its backends do genuine string<->enum conversion, no erasure to route around), while
    * `dom-facade`'s `@js.native` members stay `String`-typed on the native declaration itself (required — see
    * [[enumAccessors]]) and get an ADDITIVE `fromDom`-backed extension accessor for ergonomic typed access.
    *
    * Case names are camel-cased from the dom literal exactly as the legacy stringly-typed renderer did; case-name
    * collisions (two distinct dom values mangling to the same Scala identifier, e.g. `"top start"` / `"top-start"` both
    * → `TopStart`) dedupe by keeping the first-seen value, so the generated `enum` block never redeclares a case.
    */
  def enumTypes(defs: List[EnumDef]): String =
    val types = defs.map(renderEnumType).mkString("\n\n")
    s"""$header
       |package ascent.domtypes
       |
       |/** Generated real Scala 3 enums, one per WebIDL `enum` block. Platform-neutral (jvm/js/native) — every
       |  * consumer resolves the SAME type here, whether it binds through native interop or a genuine runtime
       |  * conversion boundary.
       |  *
       |  * `domValue` carries the spec-correct wire string; `fromDom` parses an untrusted string back into the enum,
       |  * returning `None` for a value the spec doesn't define (rather than throwing) since the wire value always
       |  * originates outside this program's control.
       |  */
       |
       |$types
       |""".stripMargin
  end enumTypes

  private def renderEnumType(d: EnumDef): String =
    val cases = dedupeEnumValues(d.values)
    if cases.isEmpty then s"""enum ${d.name}:
         |  case Unreachable // WebIDL enum declared zero values — placeholder so the type still exists
         |object ${d.name}:
         |  def fromDom(domValue: String): Option[${d.name}] = ${d.name}.values.find(_ => false)
         |""".stripMargin
    else
      val caseLines = cases
        .map { case (sn, dom) => s"""  case ${safeId(capitalize(sn))} extends ${d.name}("$dom")""" }
        .mkString("\n")
      s"""enum ${d.name}(val domValue: String):
         |$caseLines
         |object ${d.name}:
         |  def fromDom(domValue: String): Option[${d.name}] = ${d.name}.values.find(_.domValue == domValue)
         |""".stripMargin
    end if
  end renderEnumType

  /** Dedup enum values by their mangled Scala identifier — two distinct dom values can mangle to the same identifier
    * (e.g. `"top start"` and `"top-start"` both → `topStart`); LinkedHashMap preserves first-seen order for stable
    * diffs. Shared by [[renderEnumType]].
    */
  private def dedupeEnumValues(values: List[(String, String)]): List[(String, String)] =
    val byScalaName = scala.collection.mutable.LinkedHashMap.empty[String, String]
    values.foreach { case (sn, dom) =>
      val safe = enumValueIdent(sn)
      if !byScalaName.contains(safe) then byScalaName(safe) = dom
    }
    byScalaName.toList

  /** Mangle an enum value into a legal Scala identifier:
    *   - empty string ("" is a real WebIDL enum value, e.g. `enum Foo { "", "bar" }`) becomes `empty`
    *   - leading digits (e.g. `"3d"`) get an `_` prefix
    *   - any other char is left alone (camel-case already happened upstream)
    */
  private def enumValueIdent(s: String): String =
    if s.isEmpty then "empty"
    else if s.head.isDigit then "_" + s
    else s

  /** Uppercase the first character — real `enum` case names follow Scala convention (`Open`, not `open`), unlike the
    * legacy lowercase-first `val`s the stringly-typed renderer used to emit.
    */
  private def capitalize(s: String): String =
    if s.isEmpty then s else s.head.toUpper.toString + s.tail

  // --- dom-facade/.../generated/EnumAccessors.scala (additive, bridges @js.native String members to real enums) ---

  /** Render an ADDITIVE `extension` accessor for every `@js.native` facade/interface member whose [[FacadeMember]]
    * carries an `enumType` — one `def <name>Typed: Option[ascent.domtypes.<Enum>]` per member, parsing the native
    * `String` value via that enum's `fromDom`.
    *
    * Deliberately does NOT touch the native member itself (`Facades.scala` / `Interfaces.scala` stay untouched,
    * `mode: String` unchanged): a `@js.native def` is erased at the Scala.js boundary — there's no conversion step, so
    * the native declaration MUST match the raw wire value (`String`) or the binding silently corrupts. The typed
    * accessor lives ONLY as a separate extension method, a genuine conversion boundary layered on top, which is exactly
    * what makes exposing the strong enum type here sound.
    */
  def enumAccessors(interfaces: List[InterfaceDef], facades: List[FacadeDef]): String =
    val interfaceBlocks = interfaces.flatMap(d => renderAccessorBlock(d.name, d.attributes))
    val facadeBlocks    = facades.flatMap(d => renderAccessorBlock(d.interface, d.members))
    val blocks          = (interfaceBlocks ++ facadeBlocks).mkString("\n\n")
    s"""$header
       |package ascent.dom
       |
       |/** Additive typed-enum accessors bridging `@js.native` `String`-typed members to the real Scala 3 enums
       |  * generated in `dom-types`. See [[Renderer.enumAccessors]] for why this must be additive rather than
       |  * changing the native member's own declared type.
       |  */
       |
       |$blocks
       |""".stripMargin
  end enumAccessors

  /** One `extension` block per interface that has at least one enum-typed member — interfaces with none emit nothing at
    * all (`Nil`), so [[enumAccessors]]'s output stays free of empty/dead extension blocks.
    */
  private def renderAccessorBlock(interfaceName: String, members: List[FacadeMember]): List[String] =
    val enumMembers = members.collect { case m if m.enumType.isDefined => m }
    if enumMembers.isEmpty then Nil
    else
      val lines = enumMembers
        .map { m =>
          val enumTpe = s"ascent.domtypes.${m.enumType.get}"
          // safeId must wrap the COMBINED identifier (e.g. `typeTyped`, not `` `type` `` followed
          // by a bare `Typed` — those are two separate tokens in Scala, a syntax error).
          s"""  def ${safeId(m.name + "Typed")}: Option[$enumTpe] = $enumTpe.fromDom(self.${safeId(m.name)})"""
        }
        .mkString("\n")
      List(s"""extension (self: $interfaceName)
           |$lines""".stripMargin)
    end if
  end renderAccessorBlock

  private def renderInterface(d: InterfaceDef): String =
    val parent    = d.parent.getOrElse("js.Object")
    val attrs     = d.attributes.filterNot(a => objectMethodClashes.contains(a.name))
    val methods   = d.methods.filterNot(m => objectMethodClashes.contains(m.scalaName))
    val attrLines = attrs.map { a =>
      // Writable IDL attributes (`attribute T name`) emit as `var`; read-only (`readonly
      // attribute T name`) emit as `def`. Matches WebIDL semantics, and lets callers
      // assign to live properties (text.data = "..."; canvas.width = 320; etc.) without
      // dropping to js.Dynamic.
      val keyword = if a.readonly then "def" else "var"
      s"  $keyword ${safeId(a.name)}: ${a.scalaType} = js.native"
    }
    // Scala 3 forbids default args on multiple overloads of the same name *anywhere in
    // the inheritance chain*. Track names that are overloaded among:
    //   - own methods (the locally-emitted ones)
    //   - inherited methods declared on any ancestor (`inheritedMethodNames`)
    // For names that ARE overloaded across own+inherited, strip defaults from ALL own
    // overloads. For uniquely-named own methods, defaults are fine.
    val ownNameCounts                       = methods.groupBy(_.scalaName).view.mapValues(_.size).toMap
    def isOverloaded(name: String): Boolean =
      ownNameCounts.getOrElse(name, 0) > 1 || d.inheritedMethodNames.contains(name)
    val methodLines = methods.map { m =>
      val allowDefaults = !isOverloaded(m.scalaName)
      val params        = m.params
        .map { p =>
          val base = s"${safeId(p.name)}: ${p.scalaType}"
          if p.optional && allowDefaults then s"$base = js.native" else base
        }
        .mkString(", ")
      s"  def ${safeId(m.scalaName)}($params): ${m.returnType} = js.native"
    }
    val body      = (attrLines ++ methodLines).mkString("\n")
    val bodyBlock = if body.isEmpty then "" else s":\n$body\n"
    s"""@js.native
       |@JSGlobal
       |class ${d.name} extends $parent$bodyBlock""".stripMargin
  end renderInterface

  // --- dom-core/.../generated/Elements.scala (platform-neutral structural traits) ---

  /** Render the in-scope element/core interfaces as plain abstract Scala traits — the CONTRACT both the JS adapter
    * (wrapping real `dom-facade` instances) and the JVM/Native in-memory implementation ([[memoryImpls]]) must satisfy.
    * No `js.native`, no `@JSGlobal`, no scalajs import — this file compiles identically on jvm/js/native.
    *
    * Attribute writability follows the same WebIDL rule as [[interfaces]] (readonly → getter only, writable →
    * getter+setter), but a Scala trait can't express an abstract `var` with matching wire shape the way a
    * `@js.native var` can — so a writable attribute renders as an explicit getter/setter PAIR:
    * {{{
    *   trait HTMLAnchorElement extends HTMLElement:
    *     def href: String
    *     def href_=(value: String): Unit
    * }}}
    */
  def structuralTraits(defs: List[InterfaceDef]): String =
    val traits = defs.map(renderStructuralTrait).mkString("\n\n")
    s"""$header
       |package ascent.domcore.generated
       |
       |/** Platform-neutral structural traits, generated from the vendored webref IDL — the contract BOTH the JS
       |  * adapter (wrapping real dom-facade instances) and the in-memory JVM/Native implementation
       |  * (see [[memoryImpls]]) satisfy. Covers Node/Element/Document/EventTarget/CharacterData/Attr/Event plus
       |  * every HTML/SVG element interface reachable via createElement.
       |  */
       |
       |$traits
       |""".stripMargin
  end structuralTraits

  private def renderStructuralTrait(d: InterfaceDef): String =
    val parentClause = d.parent.map(p => s" extends $p").getOrElse("")
    val attrLines    = d.attributes.flatMap { a =>
      if a.readonly then List(s"  def ${safeId(a.name)}: ${a.scalaType}")
      else
        List(
          s"  def ${safeId(a.name)}: ${a.scalaType}",
          // safeId must wrap the COMBINED identifier (`` `type_=` ``, not `` `type`_= `` — the
          // latter is a syntax error, backticks only cover what's between them).
          s"  def ${safeId(a.name + "_=")}(value: ${a.scalaType}): Unit",
        )
    }
    val methodLines = d.methods.map { m =>
      val params = m.params.map(p => s"${safeId(p.name)}: ${p.scalaType}").mkString(", ")
      s"  def ${safeId(m.scalaName)}($params): ${m.returnType}"
    }
    val body      = (attrLines ++ methodLines).mkString("\n")
    val bodyBlock = if body.isEmpty then "" else s":\n$body"
    s"trait ${d.name}$parentClause$bodyBlock"
  end renderStructuralTrait

  // --- dom-core/.../generated (non-js) : in-memory reflection-backed implementation ---

  /** Zero-value default for a generic (non-reflected, non-overridden) mutable field's initial state — only for
    * primitives, where a real value genuinely makes sense as a starting state. Anything else (interface references,
    * `PlatformOpaque`) has no such default and is handled by [[unimplementedBody]] instead, never by this function.
    */
  private def zeroValue(scalaType: String): String = scalaType match
    case "String"  => "\"\""
    case "Boolean" => "false"
    case "Int"     => "0"
    case "Double"  => "0.0"
    case "Unit"    => "()"
    case _         => "???"

  /** Types with a genuine, meaningful zero value a field can hold — everything else (interface references,
    * `PlatformOpaque`, generated enums) has no sensible "empty" state, so those members implement the trait's abstract
    * `def` directly as `???` rather than backing a field with a fabricated placeholder value. Traits declare every
    * member as `def` (never `val`) for exactly this reason — a `def` can be implemented as `???`, thrown ONLY if
    * something actually calls it, whereas a field would need a real value to exist at all, at construction time.
    */
  private val primitiveTypesWithZeroValue: Set[String] = Set("String", "Boolean", "Int", "Double", "Unit")

  /** Types the reflected-attribute path can auto-implement against the attribute map — EXACTLY the set for which
    * `ascent.domcore.AttrCodec` provides a given instance (String/Boolean/Int/Double). `attributeMap.getOrElse`/ `.set`
    * both take an `AttrCodec[V]`, so a `[Reflect]`-marked attribute whose Scala type isn't one of these (real cases
    * from webref: `HTMLLinkElement.relList: DOMTokenList`, `popoverTargetElement: Element`) can't route through the
    * attribute map — no codec exists — and must fall through to the `???` path like any other non-codec-backed member.
    * `Unit` is deliberately absent (no `AttrCodec[Unit]`, and no attribute is `Unit`-typed anyway); keep this in
    * lockstep with `AttrCodec`'s given instances.
    */
  private val codecBackedReflectTypes: Set[String] = Set("String", "Boolean", "Int", "Double")

  /** For each in-scope element/core interface, emit a concrete in-memory class implementing its structural trait
    * (generated by [[structuralTraits]]).
    *
    *   - REFLECTED attributes auto-implement as read/write on the element's attribute map — zero hand code.
    *   - A PRIMITIVE-typed, non-reflected attribute falls back to a generic private mutable field with a
    *     type-appropriate zero value (a real, meaningful starting state).
    *   - Every METHOD, and every attribute whose type has no meaningful zero value (an interface reference,
    *     `PlatformOpaque`, an enum), implements the trait's abstract `def` directly as `???` — compiles fine, throws
    *     `NotImplementedError` only if actually called. This is the same "structural completeness over invented
    *     semantics" policy throughout the generator: nothing here is guessed at.
    *   - Any member named in `handWrittenOverrides` (a short, explicit `(interfaceName, memberName)` set the caller
    *     curates — see `Main.scala`) gets NOTHING generated for it; a hand-written `<Interface>Overrides.scala` trait
    *     (mixed in ahead of the generated defaults) supplies real behavior instead. Promote a member here once its
    *     default (a stored zero value, or `???`) is discovered to matter for real usage — not upfront.
    *
    * Classes chain via ordinary Scala inheritance — `HTMLAnchorElementMemory extends HTMLElementMemory`, mirroring
    * [[interfaces]]'s own-members-only emission (a concrete subclass inherits its ancestors' concrete members the
    * normal way; no need to re-flatten the whole chain). An interface with no parent extends the shared hand-written
    * `NodeMemoryBase` kernel instead.
    */
  def memoryImpls(defs: List[InterfaceDef], handWrittenOverrides: Set[(String, String)]): String =
    val classes = defs.map(d => renderMemoryImpl(d, handWrittenOverrides)).mkString("\n\n")
    s"""$header
       |package ascent.domcore.generated
       |
       |// The generated `*Memory` classes extend the hand-written kernel (NodeMemoryBase) and mix in the
       |// hand-written `<Interface>Overrides` traits — all of which live in the PARENT `ascent.domcore` package.
       |// Scala 3 does not make a parent package's members visible from a subpackage without an explicit import,
       |// so `ascent.domcore.generated` needs this even though it sits directly beneath `ascent.domcore`.
       |import ascent.domcore.*
       |
       |/** Generated in-memory implementations of the structural traits in Elements.scala. Reflected attributes
       |  * auto-implement against the element's attribute map; primitive-typed attributes fall back to a generic
       |  * mutable field; everything else (methods, and attributes with no meaningful zero value) implements the
       |  * trait's abstract `def` as `???` unless a hand-written `<Interface>Overrides` trait supplies it (see
       |  * [[Renderer.memoryImpls]] for the full policy).
       |  */
       |
       |$classes
       |""".stripMargin
  end memoryImpls

  /** `EventTarget` is the TRUE root of the DOM tree (`Node extends EventTarget`, and everything else chains up from
    * `Node`) — the only parentless interface that should extend the hand-written `NodeMemoryBase` kernel. Every other
    * parentless interface (`NodeList`, `DOMTokenList`, ...) is a genuine orphan, unrelated to the Node tree, and must
    * NOT be forced into it — that was a real bug: `Event` (parentless, per spec) would otherwise have wrongly inherited
    * `appendChild`/`parentNode`/etc. it has no business carrying.
    */
  private def renderMemoryImpl(d: InterfaceDef, overrides: Set[(String, String)]): String =
    val parent: Option[String] = d.parent match
      case Some(p)                         => Some(s"${p}Memory")
      case None if d.name == "EventTarget" => Some("NodeMemoryBase")
      case None                            => None
    val hasOverride = d.attributes.exists(a => overrides.contains(d.name -> a.name)) ||
      d.methods.exists(m => overrides.contains(d.name -> m.scalaName))
    val overrideMixin = if hasOverride then s" with ${d.name}Overrides" else ""
    val attrBlocks    = d.attributes.flatMap { a =>
      if overrides.contains(d.name -> a.name) then Nil // supplied by <Interface>Overrides.scala, not generated
      else if a.reflected && codecBackedReflectTypes.contains(a.scalaType) then
        // Auto-implement against the attribute map — ONLY when an AttrCodec[scalaType] exists. A reflected
        // attribute typed as a DOMTokenList / Element (real webref: relList, sandbox, popoverTargetElement)
        // has no codec, so it can't take this path — it falls through to the ??? branch below like any
        // other non-codec-backed member.
        val attrName = a.reflectedAttrName.getOrElse(a.name)
        List(
          s"""  def ${safeId(a.name)}: ${a.scalaType} = attributeMap.getOrElse("$attrName", ${zeroValue(
              a.scalaType
            )})""",
          s"""  def ${safeId(a.name + "_=")}(value: ${a.scalaType}): Unit = attributeMap.set("$attrName", value)""",
        )
      else if primitiveTypesWithZeroValue.contains(a.scalaType) then
        if a.readonly then
          // A readonly primitive is never assigned, so a backing `private var` would be an unset
          // mutable field (Scala 3's E198 warning under -Wunused:all). Nothing in the in-memory model
          // sets a readonly attribute, so the getter just returns the type's zero value directly.
          List(s"""  def ${safeId(a.name)}: ${a.scalaType} = ${zeroValue(a.scalaType)}""")
        else
          val fieldName = s"_${a.name}"
          List(
            s"""  private var $fieldName: ${a.scalaType} = ${zeroValue(a.scalaType)}""",
            s"""  def ${safeId(a.name)}: ${a.scalaType} = $fieldName""",
            s"""  def ${safeId(a.name + "_=")}(value: ${a.scalaType}): Unit = $fieldName = value""",
          )
      else
        // No meaningful zero value for this type (interface reference / PlatformOpaque / enum) —
        // implement the abstract def directly as ???, not a field. See memoryImpls' scaladoc.
        // safeId must wrap the COMBINED identifier (`` `type_=` ``, not `` `type`_= `` — a syntax
        // error, since backticks only cover what's literally between them).
        List(s"""  def ${safeId(a.name)}: ${a.scalaType} = ???""") ++
          (if a.readonly then Nil else List(s"""  def ${safeId(a.name + "_=")}(value: ${a.scalaType}): Unit = ???"""))
    }
    val methodBlocks = d.methods.collect {
      case m if !overrides.contains(d.name -> m.scalaName) =>
        val params = m.params.map(p => s"${safeId(p.name)}: ${p.scalaType}").mkString(", ")
        s"""  def ${safeId(m.scalaName)}($params): ${m.returnType} = ???"""
    }
    val members      = (attrBlocks ++ methodBlocks).mkString("\n")
    val body         = if members.isEmpty then "" else s":\n$members"
    val parentClause = parent.map(p => s"$p with ").getOrElse("")
    s"class ${d.name}Memory extends $parentClause${d.name}$overrideMixin$body"
  end renderMemoryImpl

  // --- dom-core/.../generated/ElementFactory.scala (tag-name -> Memory-class dispatch table) ---

  /** Render the tag-name -> `*Memory` constructor dispatch table `Document.createElement` (via the hand-written
    * `DocumentOverrides`) and `Node.cloneNode` (via the hand-written `NodeOverrides`) both need to construct the right
    * concrete element for a given HTML/SVG tag name. Generated from the SAME element catalog `Elements.scala`
    * (dom-types) and `elementInterfaceClosure` (this file's structural DOM scoping) already consume — hand- enumerating
    * ~140+ tag -> class mappings by hand would be impractical to keep in sync with a webref re-vendor.
    *
    * `fallbackInterface` is `HTMLUnknownElement` in real usage — the SAME interface the HTML spec itself assigns to any
    * tag name a user agent doesn't recognize (webref's own element catalog already routes several obsolete tags there,
    * e.g. `<applet>`/`<bgsound>`), so an unrecognized tag constructs a real, spec-sanctioned element type rather than
    * throwing or fabricating a special case.
    */
  def elementFactory(defs: List[ElementDef], fallbackInterface: String): String =
    // Dedup by tag name, first-wins. HTML and SVG share several tag names (`title`, `style`,
    // `script`, `a`, `path`); with HTML defs listed first (see Generator), the HTML interface wins
    // — matching `createElement`, which is HTML-namespaced (SVG elements go through createElementNS,
    // not modeled here). Without dedup the second entry is an unreachable `case` (Scala 3 E030).
    val seenTags = scala.collection.mutable.LinkedHashSet.empty[String]
    val cases    = defs
      .collect { case d if seenTags.add(d.domName) => s"""      case "${d.domName}" => ${d.interface}Memory()""" }
      .mkString("\n")
    s"""$header
       |package ascent.domcore.generated
       |
       |/** Tag-name -> concrete `*Memory` element dispatch table, generated from the vendored webref element
       |  * catalogs (the SAME catalog `dom-types`' `Elements.scala` and this file's own structural DOM scoping
       |  * consume). Used by `DocumentOverrides.createElement` and `NodeOverrides.cloneNode` — the two places that
       |  * construct a fresh concrete element from a bare tag name.
       |  */
       |object ElementFactory:
       |  /** Construct the concrete `*Memory` for a tag, then STAMP its node identity: `nodeNameRef` = the tag
       |    * (so `Element.tagName` / `Node.nodeName` report it) and `nodeTypeRef` = 1 (`Node.ELEMENT_NODE`). A
       |    * no-arg `*Memory` constructor can't know either on its own — this is the single choke point that
       |    * teaches every freshly-created element what it is. Tag names are lowercased to match HTML's
       |    * ASCII-case-insensitive tag matching (the css selector engine compares case-sensitively).
       |    */
       |  def createByTag(tagName: String): ascent.domcore.generated.Element =
       |    val lower = tagName.toLowerCase
       |    val el: ascent.domcore.NodeMemoryBase & ascent.domcore.generated.Element = (lower match
       |$cases
       |      case _ => ${fallbackInterface}Memory()
       |    )
       |    el.nodeNameRef = lower
       |    el.nodeTypeRef = 1
       |    el
       |
       |  def createText(data: String): ascent.domcore.generated.Text =
       |    val t = ascent.domcore.generated.TextMemory()
       |    t.data = data
       |    t.nodeNameRef = "#text"
       |    t.nodeTypeRef = 3
       |    t
       |
       |  def createComment(data: String): ascent.domcore.generated.Comment =
       |    val c = ascent.domcore.generated.CommentMemory()
       |    c.data = data
       |    c.nodeNameRef = "#comment"
       |    c.nodeTypeRef = 8
       |    c
       |""".stripMargin
  end elementFactory

end Renderer
