// AUTO-GENERATED by ascent-domgen. Do not edit by hand — see domgen/README.md to regenerate.

package ascent.domtypes.tags

/** Phantom markers for HTML element interfaces.
  *
  * An attribute key is typed at the interface that introduces the content attribute. These are not DOM nodes.
  */
sealed trait Element
trait HTMLElement                extends Element
trait HTMLHtmlElement            extends HTMLElement
trait HTMLHeadElement            extends HTMLElement
trait HTMLTitleElement           extends HTMLElement
trait HTMLBaseElement            extends HTMLElement
trait HTMLLinkElement            extends HTMLElement
trait HTMLMetaElement            extends HTMLElement
trait HTMLStyleElement           extends HTMLElement
trait HTMLBodyElement            extends HTMLElement
trait HTMLHeadingElement         extends HTMLElement
trait HTMLParagraphElement       extends HTMLElement
trait HTMLHRElement              extends HTMLElement
trait HTMLPreElement             extends HTMLElement
trait HTMLQuoteElement           extends HTMLElement
trait HTMLOListElement           extends HTMLElement
trait HTMLUListElement           extends HTMLElement
trait HTMLMenuElement            extends HTMLElement
trait HTMLLIElement              extends HTMLElement
trait HTMLDListElement           extends HTMLElement
trait HTMLDivElement             extends HTMLElement
trait HTMLAnchorElement          extends HTMLElement
trait HTMLDataElement            extends HTMLElement
trait HTMLTimeElement            extends HTMLElement
trait HTMLSpanElement            extends HTMLElement
trait HTMLBRElement              extends HTMLElement
trait HTMLModElement             extends HTMLElement
trait HTMLPictureElement         extends HTMLElement
trait HTMLSourceElement          extends HTMLElement
trait HTMLImageElement           extends HTMLElement
trait HTMLIFrameElement          extends HTMLElement
trait HTMLEmbedElement           extends HTMLElement
trait HTMLObjectElement          extends HTMLElement
trait HTMLMediaElement           extends HTMLElement
trait HTMLVideoElement           extends HTMLMediaElement
trait HTMLAudioElement           extends HTMLMediaElement
trait HTMLTrackElement           extends HTMLElement
trait HTMLMapElement             extends HTMLElement
trait HTMLAreaElement            extends HTMLElement
trait HTMLTableElement           extends HTMLElement
trait HTMLTableCaptionElement    extends HTMLElement
trait HTMLTableColElement        extends HTMLElement
trait HTMLTableSectionElement    extends HTMLElement
trait HTMLTableRowElement        extends HTMLElement
trait HTMLTableCellElement       extends HTMLElement
trait HTMLFormElement            extends HTMLElement
trait HTMLLabelElement           extends HTMLElement
trait HTMLInputElement           extends HTMLElement
trait HTMLButtonElement          extends HTMLElement
trait HTMLSelectElement          extends HTMLElement
trait HTMLDataListElement        extends HTMLElement
trait HTMLOptGroupElement        extends HTMLElement
trait HTMLOptionElement          extends HTMLElement
trait HTMLTextAreaElement        extends HTMLElement
trait HTMLOutputElement          extends HTMLElement
trait HTMLProgressElement        extends HTMLElement
trait HTMLMeterElement           extends HTMLElement
trait HTMLFieldSetElement        extends HTMLElement
trait HTMLLegendElement          extends HTMLElement
trait HTMLSelectedContentElement extends HTMLElement
trait HTMLDetailsElement         extends HTMLElement
trait HTMLDialogElement          extends HTMLElement
trait HTMLScriptElement          extends HTMLElement
trait HTMLTemplateElement        extends HTMLElement
trait HTMLSlotElement            extends HTMLElement
trait HTMLCanvasElement          extends HTMLElement
trait HTMLUnknownElement         extends HTMLElement
trait HTMLDirectoryElement       extends HTMLElement
trait HTMLFrameElement           extends HTMLElement
trait HTMLFrameSetElement        extends HTMLElement
trait HTMLParamElement           extends HTMLElement
trait HTMLFontElement            extends HTMLElement
trait HTMLMarqueeElement         extends HTMLElement
