import zipx.plugin.ZipxPlugin.autoImport.PublishedRow

/** Writes the docs' `Released` object: each Ship row's catalog number, which is what the row's modules publish at. */
object ReleasedGen:
  def source(rows: Seq[PublishedRow]): String =
    val vals = rows
      .map(r => (name(r.identity), r.version: String))
      .sortBy(_._1)
      .map((n, v) => s"""  val $n: String = "$v"""")
      .mkString("\n")
    s"""package ascent.docs
       |
       |/** The release number of each Ship row in project/ZipxVersions.scala, generated by the build. Do not edit. */
       |object Released:
       |$vals
       |""".stripMargin
  /** A JS-only module's row names its `JS` project; the docs name the module. */
  private def name(identity: String): String =
    if identity.endsWith("JS") && identity.length > 2 then identity.dropRight(2) else identity
end ReleasedGen
