/** The docs' `Released` object: each Ship row's latest Central release, not the next number the catalog is holding.
  *
  * `source` and `latestRelease` are pure. `ReleasedLookup` does the fetch.
  */
object ReleasedGen:

  /** Highest `major.minor.patch` in a Maven `maven-metadata.xml`. Snapshots and `-ci` builds are not releases. */
  def latestRelease(xml: String): Option[String] =
    versionsIn(xml).filter(isRelease).maxOption(using releaseOrder)

  /** A JS-only module's row names its `JS` project; the docs name the module. */
  def scalaName(identity: String): String =
    if identity.endsWith("JS") && identity.length > 2 then identity.dropRight(2) else identity

  def source(rows: Seq[(String, String)]): String =
    val vals = rows.sortBy(_._1).map((n, v) => s"""  val $n: String = "$v"""").mkString("\n")
    s"""package ascent.docs
       |
       |/** Latest Central release of each Ship row. Generated by the build. Do not edit. */
       |object Released:
       |$vals
       |""".stripMargin

  /** Fails the docs compile when the parser drifts. Runs from `ReleasedLookup` before any fetch. */
  def check(): Unit =
    val xml =
      """<versions><version>0.9.0</version><version>0.10.0-ci</version><version>0.10.1-SNAPSHOT</version><version>0.10.0</version><version>0.3.0</version></versions>"""
    val picked = latestRelease(xml)
    if picked != Some("0.10.0") then sys.error(s"latestRelease picked $picked, expected 0.10.0")
    if latestRelease("<metadata></metadata>").nonEmpty then sys.error("latestRelease invented a version")
    val names = List(
      "jsJS" -> "js",
      "datastarJsJS" -> "datastarJs",
      "datastarJs" -> "datastarJs",
      "css" -> "css",
      "JS" -> "JS",
    )
    names.foreach { (in, out) =>
      val got = scalaName(in)
      if got != out then sys.error(s"scalaName($in) = $got, expected $out")
    }

  private val VersionTag = """<version>([^<]+)</version>""".r
  private val ReleaseNumber = """\d+\.\d+\.\d+""".r

  private def versionsIn(xml: String): List[String] =
    VersionTag.findAllMatchIn(xml).map(_.group(1).nn.trim).toList

  private def isRelease(version: String): Boolean =
    ReleaseNumber.matches(version)

  private val releaseOrder: Ordering[String] = Ordering.by { version =>
    version.split('.').nn.toList match
      case major :: minor :: patch :: Nil => (BigInt(major), BigInt(minor), BigInt(patch))
      case _                               => (BigInt(0), BigInt(0), BigInt(0))
  }
end ReleasedGen
