package ascent.domgen.css

import ascent.domgen.Renderer

/** A property as the renderer accepts it: a Scala name, the dom name, the analyzed shape, and an optional
  * grammar-parse-error string. When `parseError` is present the renderer emits a leading `// could not parse: ...`
  * comment so reviewers see grammar regressions inline in the diff.
  */
final case class PropertyDef(
    scalaName: String,
    domName: String,
    shape: PropertyShape,
    parseError: Option[String] = scala.None,
    doc: Option[String] = scala.None,
)

/** Renders a list of [[PropertyDef]]s into the body of `StylesGenerated.scala`.
  *
  * Each property becomes one `object <scalaName> extends DS("<domName>") <with traits>` declaration; if the property
  * has any extra keyword methods, they are appended as a `:`-block body. Output is committed to
  * `css/.../generated/StylesGenerated.scala` and mixed into `object Styles` via `extends StylesGenerated`.
  */
object CssRenderer:

  private val header =
    """// AUTO-GENERATED by ascent-domgen. Do not edit by hand — see domgen/README.md to regenerate.
      |""".stripMargin

  /** Method names that would clash with `java.lang.Object` members and CANNOT be resolved by back-ticking (the binding
    * still collides because `Object.clone()` is inherited). The renderer suffixes these with a `_` to disambiguate; the
    * rendered CSS stays unchanged.
    */
  private val objectMethodClashes: Set[String] = Set(
    "clone",
    "wait",
    "notify",
    "notifyAll",
    "finalize",
  )

  private def safeMethodName(scalaName: String): String =
    if objectMethodClashes.contains(scalaName) then scalaName + "Css"
    else Renderer.safeId(scalaName)

  /** Render one property definition into a single source-level snippet. The result is a complete `object ...`
    * declaration possibly followed by a `:`-block body of methods, optionally preceded by a `// could not parse: ...`
    * comment when the property's grammar failed to parse.
    */
  def renderProperty(d: PropertyDef, closures: Map[String, Map[String, KeywordResolution.Reach]] = Map.empty): String =
    val safeObj    = Renderer.safeId(d.scalaName)
    val withs      = d.shape.traits.map(t => s"with $t").mkString(" ")
    val scaladoc   = d.doc.map(scaladocBlock(_, "")).getOrElse("")
    val errComment = d.parseError match
      case scala.None => ""
      case Some(msg)  =>
        // Collapse newlines so the comment stays on one line.
        s"// could not parse: ${msg.replace('\n', ' ').replace('\r', ' ').take(160)}\n"
    val header =
      if withs.isEmpty then s"""$scaladoc${errComment}object $safeObj extends DS("${d.domName}")"""
      else s"""$scaladoc${errComment}object $safeObj extends DS("${d.domName}") $withs"""
    // Drop own keywords a mixed-in trait already provides; emit `override def` for diamond keywords (declared by ≥2
    // independent mixed-in traits) so the inherited ambiguity is resolved at the concrete site.
    val resolved = KeywordResolution.resolve(d.shape.keywords, d.shape.traits, closures)
    // Body pad is 2, not 4: renderTrait wraps each property in `indent(_, "  ")`, so a 2-space body
    // member lands at the 4-space column scalafmt expects (matches renderValueTrait).
    val body = renderKeywordBody(resolved, "  ")
    if body.isEmpty then header else s"$header:\n$body"
  end renderProperty

  /** Render the resolved keyword body: kept own defs, then any `override def`s for diamonds. */
  private def renderKeywordBody(r: KeywordResolution.Resolved, pad: String): String =
    val kept      = renderKeywordDefs(r.kept, pad)
    val overrides = r.overrides
      .map(k => s"""${pad}override def ${safeMethodName(k.scalaName)}: Declaration = apply("${k.domName}")""")
      .mkString("\n")
    List(kept, overrides).filter(_.nonEmpty).mkString("\n")

  /** Render keyword `def`s, each optionally preceded by its scaladoc. When NONE carry docs we align the `=` columns
    * (reads like hand-written `Styles.scala`); when any carry docs, alignment is dropped (a doc block between defs
    * makes column alignment meaningless and noisy).
    */
  private def renderKeywordDefs(keywords: List[KeywordMethod], pad: String): String =
    if keywords.isEmpty then ""
    else
      val anyDoc = keywords.exists(_.doc.nonEmpty)
      renderKeywordDefsNonEmpty(keywords, pad, anyDoc)

  private def renderKeywordDefsNonEmpty(keywords: List[KeywordMethod], pad: String, anyDoc: Boolean): String =
    if anyDoc then
      keywords
        .map { k =>
          val doc = k.doc.map(scaladocBlock(_, pad)).getOrElse("")
          s"""$doc${pad}def ${safeMethodName(k.scalaName)}: Declaration = apply("${k.domName}")"""
        }
        .mkString("\n")
    else
      val widest = keywords.map(k => safeMethodName(k.scalaName).length).max
      keywords
        .map { k =>
          val sid = safeMethodName(k.scalaName)
          val gap = " " * (widest - sid.length)
          s"""${pad}def $sid: Declaration $gap= apply("${k.domName}")"""
        }
        .mkString("\n")
  end renderKeywordDefsNonEmpty

  /** A one-line scaladoc block at the given indent: `/** … */`. Collapses newlines and truncates so the comment stays
    * tidy in the generated source.
    */
  private def scaladocBlock(text: String, pad: String): String =
    val clean = text.replace('\n', ' ').replace('\r', ' ').replaceAll("\\s+", " ").trim.take(240)
    if clean.isEmpty then "" else s"$pad/** $clean */\n"

  /** Render the full source file: header + package + a `trait StylesGenerated` containing one inner object per
    * property. `StylesGenerated extends StylesValueTraits` so the generated value-type traits (`LineWidth`, …) are in
    * scope by simple name for the property objects' `with …` clauses.
    */
  def renderTrait(defs: List[PropertyDef], catalog: List[ValueTrait] = Nil): String =
    val closures = KeywordResolution.closures(catalog)
    val body     = defs.map(d => indent(renderProperty(d, closures), "  ")).mkString("\n\n")
    val mixin    = if catalog.isEmpty then "" else " extends StylesValueTraits"
    s"""$header
       |package ascent.css
       |
       |import StylesFoundation.*
       |
       |/** Generated CSS property catalog. Mixed into `object Styles` via
       |  * `Styles extends StylesGenerated`, so users see them at the same call site as the
       |  * hand-written foundation traits (Length / Percent / ColorLike / Auto / None / Normal /
       |  * Numeric) and the generated value-type traits (see [[StylesValueTraits]]).
       |  */
       |trait StylesGenerated$mixin:
       |$body
       |""".stripMargin
  end renderTrait

  /** Render the value-type-trait catalog file: one `trait <Name> extends DS` per shared keyword-bearing CSS `<type>`,
    * carrying its keyword `def`s (with webref prose as scaladoc). Properties mix these in (`with LineWidth`) instead of
    * inlining the same keywords — see [[ValueTrait]].
    */
  def renderValueTraits(catalog: List[ValueTrait]): String =
    val closures = KeywordResolution.closures(catalog)
    val body     = catalog.map(t => indent(renderValueTrait(t, closures), "  ")).mkString("\n\n")
    s"""$header
       |package ascent.css
       |
       |import StylesFoundation.*
       |
       |/** Generated CSS value-type traits — reusable keyword bundles for shared CSS `<type>`s (`<line-width>`,
       |  * `<line-style>`, …). A property whose grammar references such a type mixes in the matching trait, so its
       |  * keywords are defined once here rather than inlined on every referencing property. Mixed into the property
       |  * catalog via `StylesGenerated extends StylesValueTraits`.
       |  */
       |trait StylesValueTraits:
       |$body
       |""".stripMargin
  end renderValueTraits

  /** Render a single value-type trait. Composes the foundation keyword-traits it carries (`extends DS with None`)
    * rather than re-declaring `auto`/`none`/`normal`, so a property mixing both `with None` and this trait sees one
    * definition.
    */
  private def renderValueTrait(t: ValueTrait, closures: Map[String, Map[String, KeywordResolution.Reach]]): String =
    val doc = t.grammar match
      case scala.None    => s"`<${t.typeName}>`"
      case Some(grammar) => s"`<${t.typeName}>` — `$grammar`"
    val extendsClause = ("DS" :: t.extendsTraits).mkString(" with ")
    val docBlock      = scaladocBlock(doc, "")
    // Resolve against the traits this one composes: drop own keywords a parent already provides, and `override`
    // diamond keywords two composed parents both declare.
    val resolved = KeywordResolution.resolve(t.keywords, t.extendsTraits, closures)
    val body     = renderKeywordBody(resolved, "  ")
    if body.isEmpty then s"${docBlock}trait ${t.traitName} extends $extendsClause"
    else s"${docBlock}trait ${t.traitName} extends $extendsClause:\n$body"
  end renderValueTrait

  /** Render the keyword-value-enum file: one top-level `enum <Name> extends CssValue` per shorthand-component keyword
    * `<type>`, whose cases render bare tokens (`both`, `alternate`, `infinite`). These are the COMPOSABLE value form
    * (spliced into a typed shorthand), sibling to the property-bound keyword traits in [[renderValueTraits]]. Coexists
    * with the same-named nested trait (different scope), exactly as hand-authored `enum LineStyle` does.
    */
  def renderKeywordValues(catalog: List[KeywordValueEnum]): String =
    val body = catalog.map(renderKeywordValueEnum).mkString("\n\n")
    s"""$header
       |package ascent.css
       |
       |import StylesFoundation.formatDouble
       |
       |/** Generated CSS keyword VALUE enums — the composable `CssValue` form of shorthand-component keyword `<type>`s
       |  * (`<single-animation-fill-mode>`, `<repeat-style>`, …). Each case renders a bare token, so a typed shorthand
       |  * builder can splice it into a multi-token value. Sibling to the property-bound keyword traits in
       |  * [[StylesValueTraits]]: same keywords, but a value here (`SingleAnimationFillMode.Both`) vs a property-bound
       |  * `Declaration` there (`animationFillMode.both`). Attaches to a property via the universal `apply(CssValue)`.
       |  */
       |""".stripMargin + body + "\n"
  end renderKeywordValues

  private def renderKeywordValueEnum(e: KeywordValueEnum): String =
    val doc = e.grammar match
      case scala.None    => s"`<${e.typeName}>`"
      case Some(grammar) => s"`<${e.typeName}>` — `$grammar`"
    val keywordCases = e.cases.map { k =>
      val caseDoc = k.doc.map(d => scaladocBlock(d, "  ")).getOrElse("")
      s"""$caseDoc  case ${pascalCase(k.domName)} extends ${e.enumName}("${k.domName}")"""
    }
    // A `<number>` branch → a parameterized case carrying the raw number (rendered platform-stably).
    val numberCase =
      if e.hasNumber then List(s"""  /** A numeric value (e.g. an iteration count). */
                |  case Count(n: Double) extends ${e.enumName}(formatDouble(n))""".stripMargin)
      else Nil
    val cases = (keywordCases ++ numberCase).mkString("\n")
    s"""${scaladocBlock(doc, "")}enum ${e.enumName}(val render: String) extends CssValue:
       |$cases
       |
       |  override def toString: String = render
       |end ${e.enumName}""".stripMargin
  end renderKeywordValueEnum

  /** `alternate-reverse` → `AlternateReverse`, `both` → `Both`. Enum case names are PascalCase of the CSS keyword. */
  private def pascalCase(domName: String): String =
    domName.split('-').filter(_.nonEmpty).map(_.capitalize).mkString

  /** Indent every line of `text` with `pad`. */
  private def indent(text: String, pad: String): String =
    text
      .split('\n')
      .map { line =>
        if line.isEmpty then line else pad + line
      }
      .mkString("\n")

end CssRenderer
