package ascent.domgen.css

import ascent.domgen.Renderer
import ascent.domgen.css.WebrefCss.{Catalog, SelectorDef}

/** Generator for the typed selector catalogs — the *simple* (argument-less) pseudo-classes and pseudo-elements from the
  * vendored webref `selectors:` arrays (`selectors.json`, `selectors-5.json`, `css-pseudo.json`), plus the typed
  * element-tag selectors (`Tag.button`, `Tag.div`) from the same `elements/html.json` that drives `Elements`.
  *
  * Emits three traits into `css/.../generated/PseudoSelectors.scala`:
  *   - `trait PseudoClassesGenerated` — one `val hover: PseudoClass = simple("hover")` per simple pseudo-class;
  *   - `trait PseudoElementsGenerated` — one `val before: PseudoElement = simple("before")` per simple pseudo-element;
  *   - `trait ElemsGenerated` — one `val button: Sel = tag("button")` per HTML element.
  *
  * The hand-written companions [[ascent.css.PseudoClass]] / [[ascent.css.PseudoElement]] / [[ascent.css.Elem]] `extend`
  * these, so the generated `val`s sit alongside the hand-written constructors (`nthChild`, `not`, `tag(String)`, …).
  *
  * What's EXCLUDED (and why):
  *   - functional selectors (name ends `()`) — they take typed arguments, so they're hand-written;
  *   - combinator entries (`&`, `+`, `>`, `~`, `||`) — not pseudos; modeled as [[ascent.css.Sel]] methods;
  *   - legacy single-colon pseudo-elements (`:before`/`:after`/`:first-line`/`:first-letter`) — the `::` forms are the
  *     modern spelling and ARE emitted; the CSS2 single-colon aliases are deliberately dropped.
  */
object SelectorGenerator:

  private val header =
    """// AUTO-GENERATED by ascent-domgen. Do not edit by hand — see domgen/README.md to regenerate.
      |""".stripMargin

  /** The CSS2 single-colon pseudo-elements webref still lists; we emit only the modern `::` spelling, so these are
    * dropped to avoid a duplicate `val before` etc. (the `::` entry wins).
    */
  private val legacySingleColonPseudoElements: Set[String] =
    Set(":before", ":after", ":first-line", ":first-letter")

  /** A "simple" selector: a plain `:name` / `::name` with no arguments (no parens) — the only ones we can surface as a
    * nullary `val`. Functional ones (`:nth-child()`) and combinators are excluded.
    */
  private def isSimple(s: SelectorDef): Boolean =
    !s.name.endsWith("()") && s.name.startsWith(":") &&
      s.name.drop(1).dropWhile(_ == ':').forall(c => c.isLetterOrDigit || c == '-')

  private def isPseudoElement(s: SelectorDef): Boolean = s.name.startsWith("::")

  /** camelCase a hyphenated pseudo name into a Scala val identifier: `focus-visible` → `focusVisible`. */
  private def camelCase(s: String): String =
    val parts = s.split('-')
    if parts.length <= 1 then s
    else parts.head + parts.tail.map(_.capitalize).mkString

  private def scaladoc(text: String, pad: String): String =
    val clean = text.replace('\n', ' ').replace('\r', ' ').replaceAll("\\s+", " ").trim.take(240)
    if clean.isEmpty then "" else s"$pad/** $clean */\n"

  /** Render one `val` line for a simple selector. `bareName` is the pseudo name with its leading colon(s) stripped
    * (what `simple(...)` takes); `ctorMethod` is `"simple"` and `tpe` the return type.
    */
  private def renderVal(s: SelectorDef, tpe: String): String =
    val bareName  = s.name.dropWhile(_ == ':')
    val scalaName = Renderer.safeId(camelCase(bareName))
    val doc       = s.prose.map(scaladoc(_, "  ")).getOrElse("")
    s"""$doc  val $scalaName: $tpe = simple("$bareName")"""

  /** Render one element-tag `val`: `val button: Sel = tag("button")`. `domName` is the HTML element name; `scalaName`
    * is its keyword-safe Scala identifier (`object` → backticked, `class` → `className` mapping handled upstream).
    */
  private def renderTag(scalaName: String, domName: String): String =
    s"""  val ${Renderer.safeId(scalaName)}: Sel = tag("$domName")"""

  /** Build the generated traits' source. `elements` are `(scalaName, domName)` pairs from `elements/html.json` (same
    * source as `Elements`), used to emit the typed element-tag selectors.
    */
  def generate(catalog: Catalog, elements: List[(String, String)]): String =
    // De-dupe by name (the catalog is already merged, but be defensive), drop the legacy single-colon elements.
    val simple = catalog.selectors
      .filter(isSimple)
      .filterNot(s => legacySingleColonPseudoElements.contains(s.name))
      .distinctBy(_.name)

    val (elementsPseudo, classes) = simple.partition(isPseudoElement)

    // Sort by the Scala val name for a stable, reviewable diff; guard against two pseudos camel-casing to the same
    // identifier (none today, but a future webref addition could collide).
    def dedupeByScalaName(defs: List[SelectorDef]): List[SelectorDef] =
      defs.distinctBy(s => camelCase(s.name.dropWhile(_ == ':')))

    val classVals = dedupeByScalaName(classes.sortBy(_.name)).map(renderVal(_, "PseudoClass")).mkString("\n\n")
    val elemVals  = dedupeByScalaName(elementsPseudo.sortBy(_.name)).map(renderVal(_, "PseudoElement")).mkString("\n\n")
    val tagVals   = elements.distinctBy(_._1).sortBy(_._2).map(renderTag).mkString("\n")

    s"""$header
       |package ascent.css
       |
       |/** Generated simple (argument-less) pseudo-CLASSES from the webref selectors catalog. Mixed into the
       |  * hand-written `object PseudoClass`, so `PseudoClass.hover` resolves here while the functional constructors
       |  * (`nthChild`, `not`, …) live in the companion. Each `val` carries its webref prose as scaladoc.
       |  */
       |trait PseudoClassesGenerated:
       |  /** Build a simple pseudo-class from its bare name (no leading colon). Provided by `object PseudoClass`. */
       |  protected def simple(name: String): PseudoClass
       |
       |$classVals
       |end PseudoClassesGenerated
       |
       |/** Generated simple pseudo-ELEMENTS from the webref selectors catalog. Mixed into `object PseudoElement`. */
       |trait PseudoElementsGenerated:
       |  /** Build a simple pseudo-element from its bare name (no `::`). Provided by `object PseudoElement`. */
       |  protected def simple(name: String): PseudoElement
       |
       |$elemVals
       |end PseudoElementsGenerated
       |
       |/** Generated typed element-tag selectors from the HTML element catalog (`elements/html.json`, the same source
       |  * as `Elements`). Mixed into `object Elem`, so `Elem.button` / `Elem.div` resolve here while the `tag(String)`
       |  * escape hatch lives in the companion. One `val` per element; void/non-void is irrelevant to selectors.
       |  */
       |trait ElemsGenerated:
       |  /** Build a type/element selector from its tag name. Provided by `object Elem`. */
       |  protected def tag(name: String): Sel
       |
       |$tagVals
       |end ElemsGenerated
       |""".stripMargin
  end generate
end SelectorGenerator
